name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install -y libsdl2-dev libsdl2-mixer-dev
    - name: make
      run: make -C src/
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64-nightly
        path: src/rott
